spring:
  application:
    name: photocard

  datasource:
    url: jdbc:mysql://j11c205.p.ssafy.io:3308/photocard
    username: handam
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/docs/