frontend:
  servers:
    - "http://localhost:5173"
    - "http://j11c205.p.ssafy.io:3000"

spring:
  application:
    name: SCG
  cloud:
    gateway:
      routes:
        - id: user-login-signup
          uri: http://localhost:8081
          predicates:
              - Path=/login,/oauth2/**

        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: JwtAuthFilter

        - id: user-docs
          uri: http://localhost:8081
          predicates:
            - Path=/user/docs/**
          filters:
            - name: RewritePath
              args:
                regexp: /user/docs/(?<remaining>.*)
                replacement: /docs/${remaining}

        - id: feed
          uri: http://j11c205a.p.ssafy.io:8080
          predicates:
            - Path=/api/v1/feeds/**
          filters:
            - name: JwtAuthFilter

        - id: feed-docs
          uri: http://j11c205a.p.ssafy.io:8080
          predicates:
            - Path=/feeds/docs/**
          filters:
            - name: RewritePath
              args:
                regexp: /feeds/docs/(?<remaining>.*)
                replacement: /docs/${remaining}
  jwt:
    secret: ${SPRING_JWT_SECRET:saaaaaaaanggggggmiiiiiinnnnnnnnnninininiinininini}

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
