spring:
  application:
    name: SCG

  profiles:
    active: prod

server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
