spring:
  application:
    name: accompanyboard

  datasource:
    url: jdbc:mysql://j11c205.p.ssafy.io:3307/accompany_board
    username: handam
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/docs/

user:
  service:
    url: http://j11c205.p.ssafy.io:8081/api/v1

plan:
  service:
    url: http://j11c205a.p.ssafy.io:8082/api/v1