spring:
  config:
    activate:
      on-profile: test
  jwt:
    secret: ${SPRING_JWT_SECRET:saaaaaaaanggggggmiiiiiinnnnnnnnnninininiinininini}
  datasource:
    url: jdbc:h2:mem:feedApplication;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  user:
    service:
      url: http://j11c205.p.ssafy.io:8081
