spring:
  application:
    name: feed

  datasource:
    url: jdbc:h2:mem:~/feedApplcation
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/docs/
