spring:
  application:
    name: feed
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 업로드할 파일의 최대 크기 설정
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://j11c205a.p.ssafy.io:3306/feed_db
    username: handam
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

    web:
      resources:
        static-locations: classpath:/static/, classpath:/public/, classpath:/docs/


  elasticsearch:
    uris: http://j11c205a.p.ssafy.io:9200

  kafka:
    bootstrap-servers: j11c205.p.ssafy.io:9092
    consumer:
      group-id: like-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    template:
      default-topic: like-events

user:
  service:
    url: http://j11c205.p.ssafy.io:8081

hadoop:
  hdfs:
    uri: hdfs://j11c205a.p.ssafy.io:9000
    user: ubuntu
    replication: 2
