spring:
  application:
    name: feed

  datasource:
    url: jdbc:mysql://j11c205a.p.ssafy.io:3306/feed_db  # EC2 서버의 MySQL URL
    username: handam  # MySQL 사용자 아이디
    password: ssafy   # MySQL 사용자 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

    web:
      resources:
        static-locations: classpath:/static/, classpath:/public/, classpath:/docs/


  elasticsearch:
    uris: http://j11c205a.p.ssafy.io:9200

user:
  service:
    url: http://j11c205.p.ssafy.io:8081
