oauth2:
  success-redirect-url: "http://j11c205.p.ssafy.io:8080/api/v1/user/test"

spring:
  application:
    name: user
  jpa:
    hibernate:
      ddl-auto: none
  jwt:
    secret: ${SPRING_JWT_SECRET}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "http://j11c205.p.ssafy.io:8081/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name,email,nickname,gender,age,birthday,profile_image,birthyear,mobile
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8081


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j11c205.p.ssafy.io:8761/eureka
